"use client";

import { Drawer, DrawerContent, DrawerTrigger } from "@/components/ui/drawer";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";

import Image from "next/image";
import ReactionButton, { REACTIONS } from "./reaction-button";
// Assume necessary components and icons are imported correctly
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Post as PostType, Reaction } from "@/type";

const ReactionDrawer = ({ reactions }: { reactions: Reaction[] }) => {
  return (
    <Tabs defaultValue='like' className='w-full p-4 border-0'>
      <div className='w-full h-full'>
        <TabsList className='mb-4 grid w-full h-fit gap-1 grid-cols-3 grid-rows-2'>
          {Object.keys(REACTIONS).map((reactionType) => {
            return (
              <TabsTrigger value={reactionType}>
                {REACTIONS[reactionType]}
              </TabsTrigger>
            );
          })}
        </TabsList>
        {Object.keys(REACTIONS).map((reactionType) => {
          return (
            <TabsContent value={reactionType}>
              {reactions
                .filter((reaction) => reaction.reactionType === reactionType)
                .map((reaction, index) => {
                  return (
                    <div
                      key={`reaction-user-row-${index}}`}
                      className='flex gap-4 px-4'
                    >
                      <Avatar className='w-12 h-12'>
                        <AvatarImage
                          alt={reaction.username}
                          src={reaction.avatar_url as string}
                        />
                        <AvatarFallback>{reaction.username}</AvatarFallback>
                      </Avatar>
                      <div className='flex items-center justify-between'>
                        <div className='flex gap-2'>
                          <h3 className='text-lg text-gray-900'>
                            {reaction.username}
                          </h3>
                        </div>
                      </div>
                    </div>
                  );
                })}
            </TabsContent>
          );
        })}
      </div>
    </Tabs>
  );
};

const Post = ({ post, userId }: { post: PostType; userId: string }) => {
  const userReaction = post.reactions
    .filter((reaction) => reaction.user_id === userId)
    .at(0);
  console.log(userReaction);

  return (
    <div className='p-2 md:p-4 h-fit flex flex-col gap-4 bg-white'>
      <div className='flex items-start space-x-4'>
        <div className='flex-shrink-0'>
          <Avatar>
            <AvatarImage alt={post.username} src={post.avatar_url} />
            <AvatarFallback>{post.username}</AvatarFallback>
          </Avatar>
        </div>
        <div className='flex-1 flex flex-col gap-2'>
          <div className='flex items-center justify-between'>
            <div className='flex gap-2'>
              <h3 className='text-sm font-semibold text-gray-900'>
                {post.username}
              </h3>
              <p className='text-sm text-gray-500'>
                {new Date(post.created_at as string).toLocaleDateString(
                  "zh-TW"
                )}
              </p>
            </div>
          </div>
          <div className='flex gap-4'>
            <Image
              className='w-24 h-24'
              height='256'
              width='256'
              priority={true}
              src={post.picture_url}
              alt='Tin can image generated by DALLE'
            />
          </div>
          <p className='mt-3 text-sm text-gray-700'>{post.content}</p>
        </div>
      </div>
      <div className='w-full pl-12 flex gap-4 items-center'>
        <ReactionButton userReaction={userReaction} postId={post.post_id} />
        <Drawer>
          <DrawerTrigger asChild>
            <div className='cursor-pointer font-bold text-base text-gray-700 flex'>
              <div className='underline'>{post.reactions.length} 個人</div>
              按了這篇貼文表情
            </div>
          </DrawerTrigger>
          <DrawerContent className='min-h-[50vh] flex flex-col gap-4 overflow-y-scroll'>
            <ReactionDrawer reactions={post.reactions} />
          </DrawerContent>
        </Drawer>
      </div>
    </div>
  );
};

export default Post;
