"use client";
import { Drawer, DrawerContent, DrawerTrigger } from "@/components/ui/drawer";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";

import Image from "next/image";
import ReactionButton, { REACTIONS } from "./reaction-button";
// Assume necessary components and icons are imported correctly
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Post as PostType, Reaction } from "@/type";

const ReactionRow = ({ reaction }: { reaction: Reaction }) => {
  return (
    <div className='w-full flex gap-4 px-4 items-center justify-between'>
      <div className='flex gap-4 items-center'>
        <Avatar className='w-12 h-12'>
          <AvatarImage
            alt={reaction.username}
            src={reaction.avatar_url as string}
          />
          <AvatarFallback>{reaction.username}</AvatarFallback>
        </Avatar>
        <div className='flex items-center justify-between'>
          <div className='flex gap-2'>
            <h3 className='text-lg text-gray-900'>{reaction.username}</h3>
          </div>
        </div>
      </div>
      {REACTIONS[reaction.reactionType]}
    </div>
  );
};

const ReactionDrawer = ({ reactions }: { reactions: Reaction[] }) => {
  return (
    <Tabs
      defaultValue='all'
      className='w-full items-center justify-center flex flex-col  p-4 border-0'
    >
      <div className='w-full h-full max-w-[45rem]'>
        <div className='p-2 text-center text-base items-center text-gray-700 flex w-full'>
          {reactions.length} 個人按了這篇貼文表情
        </div>
        <TabsList className='mb-4 grid w-full h-fit gap-1 grid-cols-3 md:grid-cols-6'>
          {Object.keys(REACTIONS).map((reactionType) => {
            return (
              <TabsTrigger
                value={reactionType}
                className='flex gap-2 font-bold'
              >
                {REACTIONS[reactionType]}
                <div>
                  {
                    reactions.filter(
                      (reaction) => reaction.reactionType === reactionType
                    ).length
                  }
                </div>
              </TabsTrigger>
            );
          })}
        </TabsList>
        <TabsContent className='flex flex-col gap-4' value='all'>
          {reactions.map((reaction, index) => {
            return (
              <ReactionRow key={`reaction-row-${index}`} reaction={reaction} />
            );
          })}
        </TabsContent>
        {Object.keys(REACTIONS).map((reactionType) => {
          return (
            <TabsContent
              className='flex flex-col gap-4'
              key={`${reactionType}-reaction-tab`}
              value={reactionType}
            >
              {reactions
                .filter((reaction) => reaction.reactionType === reactionType)
                .map((reaction, index) => {
                  return (
                    <ReactionRow
                      key={`reaction-row-${index}`}
                      reaction={reaction}
                    />
                  );
                })}
            </TabsContent>
          );
        })}
      </div>
    </Tabs>
  );
};

const Post = ({ post, userId }: { post: PostType; userId: string }) => {
  const userReaction = post.reactions
    .filter((reaction) => reaction.user_id === userId)
    .at(0);
  console.log(userReaction);

  return (
    <div className='p-2 md:p-4 h-fit flex flex-col gap-4 bg-white'>
      <div className='flex items-start space-x-4'>
        <div className='flex-shrink-0'>
          <Avatar>
            <AvatarImage alt={post.username} src={post.avatar_url} />
            <AvatarFallback>{post.username}</AvatarFallback>
          </Avatar>
        </div>
        <div className='flex-1 flex flex-col gap-2'>
          <div className='flex items-center justify-between'>
            <div className='flex gap-2'>
              <h3 className='text-sm font-semibold text-gray-900'>
                {post.username}
              </h3>
              <p className='text-sm text-gray-500'>
                {new Date(post.created_at as string).toLocaleDateString(
                  "zh-TW"
                )}
              </p>
            </div>
          </div>
          <div className='flex gap-4'>
            <Image
              className='w-24 h-24'
              height='256'
              width='256'
              priority={true}
              src={post.picture_url}
              alt='Tin can image generated by DALLE'
            />
          </div>
          <p className='mt-3 text-sm text-gray-700'>{post.content}</p>
        </div>
      </div>
      <div className='w-full pl-12 flex gap-4 items-center'>
        <ReactionButton userReaction={userReaction} postId={post.post_id} />
        <Drawer>
          <DrawerTrigger asChild>
            <div className='cursor-pointer font-bold text-base text-gray-700 flex gap-1'>
              <div className='underline'>{post.reactions.length} 個人</div>
              <div>按了這篇貼文表情</div>
            </div>
          </DrawerTrigger>
          <DrawerContent className='min-h-[50vh] flex flex-col overflow-y-scroll'>
            <ReactionDrawer reactions={post.reactions} />
          </DrawerContent>
        </Drawer>
      </div>
    </div>
  );
};

export default Post;
